services:
  - type: web
    name: space-learning-system
    env: node
    buildCommand: pip3 install papermill scikit-learn pandas numpy requests tensorflow && cd server && npm ci
    startCommand: cd server && npm start
